### ISSUE TITLE
wechat share is broken

### ISSUE THREAD

**Issue by bmxbmx3** [theme-next/theme-next-fastclick#2]
I follow the README,the wechat share just show the QR code,but it can't jump to another link when I use phone to scan the QR code.

**Comment by qzi** [comment]
我想问一下，GitHub Page分享了后在微信会提示打开外部链接，如何能使这个外部链接认证后不会被提示呢

**Comment by stevenjoezhang** [comment]
这超出了我们的能力范围。请联系**微信客服**解决。
