### ISSUE TITLE
ERROR Plugin load failed: hexo-next-share Error: Cannot find module 'next-util'

### ISSUE THREAD

**Issue by GinWU05** [theme-next/theme-next-fastclick#6]
### What I did

1. `npm install theme-next/hexo-next-share`
2. `hexo clean && hexo g && hexo s`

### What Error I Meeted

```
INFO  98 files generated in 2.8 s
ERROR Plugin load failed: hexo-next-share
Error: Cannot find module 'next-util'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (D:\project\Fifth-Patient\node_modules\hexo\lib\hexo\index.js:219:21)
    at D:\project\Fifth-Patient\node_modules\hexo-next-share\index.js:5:14
    at fs.readFile.then.script (D:\project\Fifth-Patient\node_modules\hexo\lib\hexo\index.js:232:12)
    at tryCatcher (D:\project\Fifth-Patient\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\project\Fifth-Patient\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\project\Fifth-Patient\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\project\Fifth-Patient\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\project\Fifth-Patient\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (D:\project\Fifth-Patient\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (D:\project\Fifth-Patient\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (D:\project\Fifth-Patient\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (D:\project\Fifth-Patient\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\project\Fifth-Patient\node_modules\bluebird\js\release\promise.js:649:10)
```

### What I Try To Fixed

```
$ rm -rf ./node_modules
$ npm i
$ npm i next-until
```

edit **theme** `_config.yml` same with [README.md Likely](https://github.com/theme-next/hexo-next-share/blob/master/README.md#likely)

**result：Invalid behavior and nothing happened, no share ui append the post page.**

### What Happen Detail

- package.json change

```
"hexo-next-share": "github:theme-next/hexo-next-share"
"next-util": "^1.0.0"
```

### Version Info

- OS: win10
- hexo: 3.9.0
- hexo-theme-next: 7.7.0

### What I Say

I hope my posts can be shared to different ( social ) platforms, but...

```
ERROR Plugin load failed: hexo-next-share
Error: Cannot find module 'next-util'
```

How Should I do?
Am I configured wrong?
Or other reson?
Contact me, Please.
Chinese developer, from Google Translate

**Comment by stevenjoezhang** [comment]
You can try to remove `node_modules` and reinstall all plugins

`next-util` has been published to npm: https://www.npmjs.com/package/next-util

<blockquote><img src="https://static.npmjs.com/338e4905a2684ca96e08c7780fc68412.png" width="48" align="right"><div><img src="https://static.npmjs.com/da3ab40fb0861d15c83854c29f5f2962.png" height="14"> npm</div><div><strong><a href="https://www.npmjs.com/package/next-util">next-util</a></strong></div><div>Utilities for NexT.</div></blockquote>

**Comment by h-hg** [comment]
> 
> 
> You can try to remove `node_modules` and reinstall all plugins
> 
> `next-util` has been published to npm: https://www.npmjs.com/package/next-util
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c2b95098a1c75357906fc6e8647c87345dde79fd/68747470733a2f2f7374617469632e6e706d6a732e636f6d2f33333865343930356132363834636139366530386337373830666336383431322e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/dbe46d42a523ce8a202f6cee2a130787bdd6cdde/68747470733a2f2f7374617469632e6e706d6a732e636f6d2f64613361623430666230383631643135633833383534633239663566323936322e706e67"> npm**[next-util](https://www.npmjs.com/package/next-util)**Utilities for NexT.

I try to remove the `node_modules`
```bash
rm -rf node_modules
```
and reinstall all plugins.
```bash
cnpm i
cnpm i theme-next/hexo-next-share
```
But it still runs the same error as above.

**Comment by wwwxmu** [comment]
I remove `hexo-next-share` by:
> npm remove hexo-next-share

and then reinstall `next-util` and `hexo-next-share`:
> npm install theme-next/next-util
> npm install theme-next/hexo-next-share

Finally the problem solved!

**Comment by stevenjoezhang** [comment]
A new version has been released: https://github.com/theme-next/hexo-next-share/releases
This issue should be resolved if npm correctly recognizes the git tag

<blockquote><img src="https://avatars3.githubusercontent.com/u/32585093?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/theme-next/hexo-next-share">theme-next/hexo-next-share</a></strong></div><div>Content sharing services for NexT. Contribute to theme-next/hexo-next-share development by creating an account on GitHub.</div></blockquote>

**Comment by asdf2014** [comment]
@stevenjoezhang Encountered another issues..
```bash
$ npm install theme-next/hexo-next-share@1.1.0 -S
```

```bash
npm ERR! code ENOLOCAL
npm ERR! Could not install from "theme-next/hexo-next-share@1.1.0" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/benedictjin/.npm/_logs/2020-03-25T04_09_51_497Z-debug.log
```

**Comment by stevenjoezhang** [comment]
I don't know why 😢

```
% npm i github:theme-next/hexo-next-share
+ hexo-next-share@1.1.0
added 1 package from 1 contributor and audited 4859 packages in 43.933s

4 packages are looking for funding
  run `npm fund` for details

found 7 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by asdf2014** [comment]
@stevenjoezhang So weird.. :sweat_smile:

**Comment by sli1989** [comment]
u can try deleting package-lock.json and try again?

**Comment by asdf2014** [comment]
@sli1989 Thx for your suggestions, it still doesn't work.

**Comment by stevenjoezhang** [comment]
Have you set the registry in `npm config`? Could you please provide the output of the following command?
```
npm config list
```

**Comment by asdf2014** [comment]
Damn.. I forgot already have configured metrics-registry as a mirror address. Everything is totally fine, thank you guys. :+1:
